# DATA JUNIOR ANALYST TEST

In [69]:
import pandas as pd
from datetime import datetime
import numpy as np
from statsmodels.formula.api import ols

### Initially I just review the data, change the variable review_time to a Date Type, check if the data has some null rows and describe the data set to understand the scale of the review variables

In [70]:
df = pd.read_csv("beer_reviews.csv", delimiter=',')
df

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1586609,14359,The Defiant Brewing Company,1162684892,5.0,4.0,3.5,maddogruss,Pumpkin Ale,4.0,4.0,The Horseman's Ale,5.2,33061
1586610,14359,The Defiant Brewing Company,1161048566,4.0,5.0,2.5,yelterdow,Pumpkin Ale,2.0,4.0,The Horseman's Ale,5.2,33061
1586611,14359,The Defiant Brewing Company,1160702513,4.5,3.5,3.0,TongoRad,Pumpkin Ale,3.5,4.0,The Horseman's Ale,5.2,33061
1586612,14359,The Defiant Brewing Company,1160023044,4.0,4.5,4.5,dherling,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061
1586613,14359,The Defiant Brewing Company,1160005319,5.0,4.5,4.5,cbl2,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   brewery_id          1586614 non-null  int64
 1   brewery_name        1586599 non-null  object
 2   review_time         1586614 non-null  int64
 3   review_overall      1586614 non-null  float64
 4   review_aroma        1586614 non-null  float64
 5   review_appearance   1586614 non-null  float64
 6   review_profilename  1586266 non-null  object
 7   beer_style          1586614 non-null  object
 8   review_palate       1586614 non-null  float64
 9   review_taste        1586614 non-null  float64
 10  beer_name           1586614 non-null  object
 11  beer_abv            1518829 non-null  float64
 12  beer_beerid         1586614 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 157.4+ MB

In [72]:
# Using Describe function to check the scale of the review variables
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.518829e+06,1.586614e+06
mean,3.130099e+03,1.224089e+09,3.815581e+00,3.735636e+00,3.841642e+00,3.743701e+00,3.792860e+00,7.042387e+00,2.171279e+04
std,5.578104e+03,7.654427e+07,7.206219e-01,6.976167e-01,6.160928e-01,6.822184e-01,7.319696e-01,2.322526e+00,2.181834e+04
min,1.000000e+00,8.406720e+08,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,3.000000e+00
25%,1.430000e+02,1.173224e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.717000e+03
50%,4.290000e+02,1.239203e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.390600e+04
75%,2.372000e+03,1.288568e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.944100e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.770000e+01,7.731700e+04

In [73]:
df['review_time'] = pd.to_datetime(df['review_time'], unit='s')
df['review_time'] = df['review_time'].fillna(0)
df.dropna(subset=['review_time'], inplace=True)

In [74]:
null_counts = df.isnull().sum(axis=0)
print(null_counts)

brewery_id                0
brewery_name             15
review_time               0
review_overall            0
review_aroma              0
review_appearance         0
review_profilename      348
beer_style                0
review_palate             0
review_taste              0
beer_name                 0
beer_abv              67785
beer_beerid               0
dtype: int64

In [75]:
# I cleaned the nulls from the beer_abv field and then calculate the mean of abv by Brewery
StrongestBeer=df
StrongestBeer['beer_abv']=StrongestBeer['beer_abv'].fillna(0)
StrongestBeer.dropna(subset=['beer_abv'], inplace=True)
null_counts = df.isnull().sum(axis=0)
print(null_counts)
StrongestBeer = df.groupby(['brewery_name','beer_name'])['beer_abv'].mean()
StrongestBeer  = StrongestBeer .reset_index()
StrongestBeer  = pd.DataFrame(StrongestBeer)
pivot = StrongestBeer.pivot_table(index=['brewery_name'], values=['beer_abv'], aggfunc='mean')
StrongestBeer = pd.DataFrame(pivot)
StrongestBeer = StrongestBeer.sort_values(by='beer_abv',ascending=False)
StrongestBeer.head(10)

brewery_id              0
brewery_name           15
review_time             0
review_overall          0
review_aroma            0
review_appearance       0
review_profilename    348
beer_style              0
review_palate           0
review_taste            0
beer_name               0
beer_abv                0
beer_beerid             0
dtype: int64

                                  beer_abv
brewery_name
SchorschbrÃ¤u                     24.690000
Shoes Brewery                    15.200000
Rascal Creek Brewing Co.         13.000000
Monks Porter House               12.466667
United Brands Company            12.000000
RinkuÂški&#371; Aluas Darykla     12.000000
Nasu Kogen Beer Co. Ltd.         11.500000
Wibblers                         11.000000
Zago S.r.l.                      11.000000
Brasserie Dubuisson FrÃ¨res sprl  10.607143

## Which brewery produces the strongest beers by abv ? 

   **SchorschbrÃ¤u** with a mean by beer of *24,7*

In [76]:
#Create avariable that takes into account the 5 aspects and then get the mean of this variable by beer and the number of reviews each beer got 
df['BestBeerMean'] = df.apply(lambda row: (row['review_overall'] + row['review_aroma']+row['review_appearance']+row['review_palate']+row['review_taste'])/5, axis=1)
BestBeer = df.groupby(['beer_name']).agg({'BestBeerMean':'mean', 'beer_beerid':'size'})
BestBeer= BestBeer .reset_index()
BestBeer  = pd.DataFrame(BestBeer)
BestBeer= BestBeer.sort_values(by=['beer_beerid', 'BestBeerMean'], ascending=False)
BestBeer.head(10)

                                 beer_name  BestBeerMean  beer_beerid
900                          90 Minute IPA      4.211824         3290
26117                       India Pale Ale      3.802268         3130
36868  Old Rasputin Russian Imperial Stout      4.264159         3111
45811        Sierra Nevada Celebration Ale      4.148433         3000
52576                      Two Hearted Ale      4.241569         2728
48638                  Stone Ruination IPA      4.243417         2704
3133                  Arrogant Bastard Ale      4.183210         2704
45827               Sierra Nevada Pale Ale      4.047777         2587
48595           Stone IPA (India Pale Ale)      4.213476         2575
39649                      Pliny The Elder      4.534626         2527

## If you had to pick 3 beers to recommend to someone, how would you approach the problem ? 
I would get the mean of the 5 aspects and  I will count the number of reviews to select the top 3 with both the highher number of reviews with high Score mean , in this case I would recommend **90 Minute IPA,India Pale Ale	and Old Rasputin Russian Imperial Stout**

### To get the factors that impact the most the Quality of the beer, I calculate the correlation coefficient of the different factors with the Overall impression variable

In [77]:
correlation_matrix = df.corr()
print(correlation_matrix)

                   brewery_id  review_overall  review_aroma  \
brewery_id           1.000000       -0.009331      0.019069
review_overall      -0.009331        1.000000      0.616013
review_aroma         0.019069        0.616013      1.000000
review_appearance    0.001993        0.501732      0.561029
review_palate       -0.000499        0.701914      0.616947
review_taste        -0.002672        0.789816      0.716776
beer_abv             0.027237        0.143264      0.312770
beer_beerid          0.424097        0.003794      0.077669
BestBeerMean         0.001893        0.864188      0.835434

                   review_appearance  review_palate  review_taste  beer_abv  \
brewery_id                  0.001993      -0.000499     -0.002672  0.027237
review_overall              0.501732       0.701914      0.789816  0.143264
review_aroma                0.561029       0.616947      0.716776  0.312770
review_appearance           1.000000       0.566634      0.546980  0.253702
review_palate               0.566634       1.000000      0.734135  0.273474
review_taste                0.546980       0.734135      1.000000  0.278323
beer_abv                    0.253702       0.273474      0.278323  1.000000
beer_beerid                 0.054794       0.044510      0.030402  0.131429
BestBeerMean                0.740394       0.860215      0.906269  0.298094

                   beer_beerid  BestBeerMean
brewery_id            0.424097      0.001893
review_overall        0.003794      0.864188
review_aroma          0.077669      0.835434
review_appearance     0.054794      0.740394
review_palate         0.044510      0.860215
review_taste          0.030402      0.906269
beer_abv              0.131429      0.298094
beer_beerid           1.000000      0.049209
BestBeerMean          0.049209      1.000000

In [78]:
#Linear Regression
formula = 'review_overall ~ review_aroma + review_appearance + review_palate + review_taste'
model = ols(formula, data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         review_overall   R-squared:                       0.658
Model:                            OLS   Adj. R-squared:                  0.658
Method:                 Least Squares   F-statistic:                 7.636e+05
Date:                Fri, 22 Dec 2023   Prob (F-statistic):               0.00
Time:                        15:54:39   Log-Likelihood:            -8.7999e+05
No. Observations:             1586614   AIC:                         1.760e+06
Df Residuals:                 1586609   BIC:                         1.760e+06
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.4396      0.002    190.949      0.000       0.435       0.444
review_aroma          0.0478      0.001     66.089      0.000       0.046       0.049
review_appearance     0.0359      0.001     51.287      0.000       0.035       0.037
review_palate         0.2585      0.001    340.143      0.000       0.257       0.260
review_taste          0.5515      0.001    709.782      0.000       0.550       0.553
==============================================================================
Omnibus:                    80797.422   Durbin-Watson:                   1.794
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           306869.451
Skew:                          -0.074   Prob(JB):                         0.00
Kurtosis:                       5.149   Cond. No.                         53.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## What are the factors that impacts the quality of beer the most ?
The higher correlation coeficient for the different factors and the Overall Rating is the **Taste** and also when trying to fit a Regression Model is the variable with the highest coefficient

In [79]:
df['beer_style'].describe()

count          1586614
unique             104
top       American IPA
freq            117586
Name: beer_style, dtype: object

In [80]:
# Getting the most consistent Beer Style in Aroma and Appereance
BestStyle = df.groupby(['beer_style'])['review_aroma','review_appearance'].mean()
BestStyle= BestStyle .reset_index()
BestStyle  = pd.DataFrame(BestStyle)
BestStyle['AAMean']=BestStyle.apply(lambda row: ( row['review_aroma']+row['review_appearance'])/2, axis=1)
BestStyle = BestStyle.sort_values(by='AAMean',ascending=False)
BestStyle.head(3)

C:\Users\sesa671690\AppData\Local\Temp\ipykernel_23308\1178191683.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  BestStyle = df.groupby(['beer_style'])['review_aroma','review_appearance'].mean()

,beer_style,review_aroma,review_appearance,AAMean
11,American Double / Imperial Stout,4.160665,4.163633,4.162149
89,Russian Imperial Stout,4.076576,4.210072,4.143324
86,Quadrupel (Quad),4.132533,4.117964,4.125249

In [81]:
#Getting the beer within that Beer Style with the highest approval and higher number of reviews
BeerByStyle = df.groupby(['beer_style','beer_name']).agg({'BestBeerMean':'mean', 'beer_beerid':'size'})
BeerByStyle= BeerByStyle .reset_index()
BeerByStyle  = pd.DataFrame(BeerByStyle)
BeerByStyle=BeerByStyle.loc[BeerByStyle['beer_style'] == 'American Double / Imperial Stout']
BestBeer= BeerByStyle.sort_values(by=['beer_beerid', 'BestBeerMean'], ascending=False)
BestBeer.head(10)

,beer_style,beer_name,BestBeerMean,beer_beerid
9447,American Double / Imperial Stout,Founders Breakfast Stout,4.404037,2502
9451,American Double / Imperial Stout,Founders KBS (Kentucky Breakfast Stout),4.490217,1932
9258,American Double / Imperial Stout,Bourbon County Brand Stout,4.317544,1710
9919,American Double / Imperial Stout,World Wide Stout,4.061437,1447
9724,American Double / Imperial Stout,PÃ©chÃ© Mortel (Imperial Stout Au Cafe),4.367803,1438
9846,American Double / Imperial Stout,The Abyss,4.517776,1412
9333,American Double / Imperial Stout,Choklat,4.227796,1198
9093,American Double / Imperial Stout,AleSmith Speedway Stout,4.367284,1134
9359,American Double / Imperial Stout,Creme Brulee (Imperial Milk Stout),3.904545,1012
9174,American Double / Imperial Stout,Big Bear Black Stout,4.152841,1003

## I enjoy a beer which aroma and appearance matches the beer style. What beer should I buy ? 
The beerstyle with the highest score both by Aroma and Appereance is the **American Double / Imperial Stout** and within that category the best beer with the higest number of reviews is the **Founders Breakfast Stout**